import React from "react";

export default function ReportPreview({ data, title = "Living Rock CMS Report", period = "" }) {
  return (
    <div
      id="report-content"
      style={{
        width: "800px",
        margin: "0 auto",
        padding: "40px",
        fontFamily: "Arial, sans-serif",
        backgroundColor: "#fff",
        color: "#22223b",
        borderRadius: "8px",
        boxShadow: "0 2px 8px rgba(0,0,0,0.06)",
      }}
    >
      {/* Header */}
      <div style={{ textAlign: "center", borderBottom: "2px solid #22223b", paddingBottom: "10px", marginBottom: "20px" }}>
        <img src="/logo192.png" alt="Logo" style={{ height: "60px" }} />
        <h1 style={{ margin: "10px 0", color: "#22223b" }}>{title}</h1>
        {period && <p style={{ fontSize: "14px", color: "#4a4e69" }}>{period}</p>}
      </div>

      {/* Summary Section */}
      {data.summary && (
        <>
          <h2 style={{ borderBottom: "1px solid #ccc", paddingBottom: "5px", color: "#22223b" }}>Summary</h2>
          {Object.entries(data.summary).map(([k, v]) => (
            <p key={k} style={{ margin: 0, color: "#4a4e69" }}>
              <b>{k}:</b> {v}
            </p>
          ))}
        </>
      )}

      {/* Table Section */}
      {data.table && (
        <>
          <h2 style={{ borderBottom: "1px solid #ccc", paddingBottom: "5px", marginTop: "30px", color: "#22223b" }}>{data.table.title || "Details"}</h2>
          <table style={{ width: "100%", borderCollapse: "collapse", marginTop: "10px" }}>
            <thead>
              <tr style={{ backgroundColor: "#f2f2f2" }}>
                {data.table.columns.map((col) => (
                  <th key={col} style={{ border: "1px solid #ccc", padding: "8px", color: "#22223b" }}>{col}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {data.table.rows.map((row, idx) => (
                <tr key={idx} style={{ backgroundColor: idx % 2 === 0 ? "#fff" : "#f8f9fa" }}>
                  {row.map((cell, i) => (
                    <td key={i} style={{ border: "1px solid #ccc", padding: "8px", color: "#22223b" }}>{cell}</td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </>
      )}

      {/* Footer */}
      <div
        style={{
          textAlign: "center",
          marginTop: "40px",
          fontSize: "12px",
          color: "#4a4e69",
          borderTop: "1px solid #ccc",
          paddingTop: "10px",
        }}
      >
        Generated by Living Rock CMS
      </div>
    </div>
  );
} 